sudo: false

language: cpp

os:
  # - linux
  - osx

env:
  - TASK=python_test
  - TASK=r_test

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libxml2-dev

install:
  - source tests/travis/setup.sh

script:
  - tests/travis/run_test.sh
